spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.178/choosetest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-producer
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/