server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
spring:
  application:
    name: service-manager
  mvc:
    static-path-pattern: /**
feign:
  hystrix:
    enabled: true